# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven 6-NOv-2023

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 1. Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: 2. Clear with Maven
      run: mvn clean
    - name: 3. Compile with Maven
      run: mvn compile
    - name: 4. Test with Maven
      run: mvn test
    - name: 5. Build with Maven
      run: mvn -B package --file pom.xml
